### 라이브러리를 이용해서 데이터 수집

- yahoo finance
    - 글로벌 주식 및 회사 데이터를 로드
- 한국 거래소 정보를 가져오는 라이브러리 (pykrx)
    - 한국 회사들에 대한 데이터 로드

- 실시간 데이터는 불가능
    - pykrx는 일별 주식 가격 조회
    - yfinance는 시간별로 조회 가능 (기간이 굉장히 짧음), 실시간은 아님(한 20분~30분 정도의 차이가 존재)

- 실시간 데이터를 로드하려면 증권사 api 사용
    - 증권사 계정이 존재 (개인 계정 가능)
        - 은행 계좌 등록
        - 별도의 api key 발급

In [1]:
# 라이브러리 설치
# !pip install yfinance pykrx

In [2]:
import yfinance as yf

In [3]:
# 특정 종목의 데이터를 가져온다.

ticker1 = "005930.KS"
samsung = yf.Ticker(ticker1)

In [4]:
samsung.history()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-03-23 00:00:00+09:00,190500.0,191200.0,186300.0,186300.0,30268173,0.0,0.0
2026-03-24 00:00:00+09:00,195500.0,196000.0,185500.0,189700.0,25458914,0.0,0.0
2026-03-25 00:00:00+09:00,193700.0,196400.0,189000.0,189000.0,22995904,0.0,0.0
2026-03-26 00:00:00+09:00,185500.0,185900.0,178900.0,180100.0,32074131,0.0,0.0
2026-03-27 00:00:00+09:00,172100.0,181700.0,172000.0,180100.0,29138966,0.0,0.0
2026-03-30 00:00:00+09:00,171000.0,176650.0,170600.0,176300.0,22269147,0.0,0.0
2026-03-31 00:00:00+09:00,170000.0,174700.0,167000.0,167200.0,38659593,0.0,0.0
2026-04-01 00:00:00+09:00,179000.0,190800.0,178000.0,189650.0,32390251,0.0,0.0
2026-04-02 00:00:00+09:00,192600.0,193600.0,175000.0,178400.0,38615231,0.0,0.0
2026-04-03 00:00:00+09:00,184200.0,187200.0,182700.0,186200.0,20194447,0.0,0.0
2026-04-06 00:00:00+09:00,190900.0,194600.0,190100.0,193100.0,20635958,0.0,0.0
2026-04-07 00:00:00+09:00,202000.0,202500.0,192400.0,196500.0,30848053,0.0,0.0
2026-04-08 00:00:00+09:00,214000.0,214500.0,207500.0,210500.0,35890973,0.0,0.0
2026-04-09 00:00:00+09:00,207000.0,207500.0,202000.0,204000.0,42320839,0.0,0.0
2026-04-10 00:00:00+09:00,208500.0,211000.0,205500.0,206000.0,18244459,0.0,0.0
2026-04-13 00:00:00+09:00,198200.0,203000.0,198200.0,201000.0,19603415,0.0,0.0
2026-04-14 00:00:00+09:00,208000.0,210000.0,205500.0,206500.0,23672078,0.0,0.0
2026-04-15 00:00:00+09:00,215000.0,215500.0,210000.0,211000.0,24092884,0.0,0.0
2026-04-16 00:00:00+09:00,212000.0,218000.0,210500.0,217500.0,21499788,0.0,0.0
2026-04-17 00:00:00+09:00,217000.0,218000.0,215000.0,216000.0,18079322,0.0,0.0
2026-04-20 00:00:00+09:00,214500.0,219000.0,213000.0,214500.0,17107741,0.0,0.0
2026-04-21 00:00:00+09:00,218000.0,220000.0,216000.0,219000.0,16752132,0.0,0.0
2026-04-22 00:00:00+09:00,218500.0,222500.0,215500.0,217500.0,16823480,0.0,0.0
2026-04-23 00:00:00+09:00,223000.0,229500.0,216000.0,224500.0,33874721,0.0,0.0

In [5]:
# history()
    # interval: 주기
    # period: 기간 설정 (1d, 5d, 1mo, 3mo, 6mo, 1y, 2y)

samsung.history(period='5d', interval='1m')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2026-04-17 09:00:00+09:00,217000.0,218000.0,217000.0,217250.0,0,0.0,0.0
2026-04-17 09:01:00+09:00,217250.0,218000.0,216500.0,216500.0,138510,0.0,0.0
2026-04-17 09:02:00+09:00,217000.0,217500.0,216500.0,216500.0,64171,0.0,0.0
2026-04-17 09:03:00+09:00,216500.0,217000.0,216000.0,216000.0,132867,0.0,0.0
2026-04-17 09:04:00+09:00,216500.0,216500.0,216000.0,216000.0,80982,0.0,0.0
...,...,...,...,...,...,...,...
2026-04-23 14:55:00+09:00,224500.0,225000.0,224500.0,224500.0,21110,0.0,0.0
2026-04-23 14:56:00+09:00,224500.0,225000.0,224500.0,224500.0,18468,0.0,0.0
2026-04-23 14:57:00+09:00,224500.0,225000.0,224500.0,224500.0,22205,0.0,0.0
2026-04-23 14:58:00+09:00,225000.0,225000.0,224500.0,225000.0,44561,0.0,0.0
2026-04-23 14:59:00+09:00,224750.0,225000.0,224750.0,224750.0,73362,0.0,0.0

In [ ]:
samsung.actions

In [8]:
# pykrx 라이브러리

from pykrx import stock

In [19]:
tickers = stock.get_market_ticker_list("20260401")
tickers

Error occurred in get_market_ticker_and_name: Expecting value: line 1 column 1 (char 0)

[]

In [21]:
stock.get_market_ticker_name('005930')

'삼성전자'

In [22]:
# OHLCV 확인
stock.get_market_ohlcv("20260101", "20260423", "005930")

                시가      고가      저가      종가       거래량       등락률
날짜
2026-01-02  120200  128500  120200  128500  30463279  7.172644
2026-01-05  134600  138600  133600  138100  42863376  7.470817
2026-01-06  135300  139300  132700  138900  45321341  0.579290
2026-01-07  143500  144400  137600  141000  46317413  1.511879
2026-01-08  138300  144500  138300  138800  41449329 -1.560284
...            ...     ...     ...     ...       ...       ...
2026-04-17  217000  218000  215000  216000  18079322 -0.689655
2026-04-20  214500  219000  213000  214500  17107741 -0.694444
2026-04-21  218000  220000  216000  219000  16752132  2.097902
2026-04-22  218500  222500  215500  217500  16823480 -0.684932
2026-04-23  223000  229500  216000  224500  33874721  3.218391

[76 rows x 6 columns]

In [20]:
!pip install finance-datareader

Collecting finance-datareader
  Downloading finance_datareader-0.9.110-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: beautifulsoup4 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from finance-datareader) (4.14.3)
Requirement already satisfied: lxml in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from finance-datareader) (6.0.4)
Requirement already satisfied: pandas>=1.1.0 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from finance-datareader) (2.3.3)
Collecting plotly (from finance-datareader)
  Downloading plotly-6.7.0-py3-none-any.whl.metadata (8.6 kB)
Collecting requests-file (from finance-datareader)
  Downloading requests_file-3.0.1-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: requests>=2.3.0 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from finance-datareader) (2.33.1)
Collecting tqdm (from finance-datareader)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.1.0->finance-datareader) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hkssn\appdata\roaming\python\python314\site-packages (from pandas>=1.1.0->finance-datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.1.0->finance-datareader) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.1.0->finance-datareader) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\hkssn\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas>=1.1.0->finance-datareader) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from requests>=2.3.0->finance-datareader) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from requests>=2.3.0->finance-datareader) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from requests>=2.3.0->finance-datareader) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from requests>=2.3.0->finance-datareader) (2026.2.25)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from beautifulsoup4->finance-datareader) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from beautifulsoup4->finance-datareader) (4.15.0)
Collecting narwhals>=1.15.1 (from plotly->finance-datareader)
  Downloading narwhals-2.20.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: packaging in c:\users\hkssn\appdata\roaming\python\python314\site-packages (from plotly->finance-datareader) (26.0)
Requirement already satisfied: colorama in c:\users\hkssn\appdata\roaming\python\python314\site-packages (from tqdm->finance-datareader) (0.4.6)
Downloading finance_datareader-0.9.110-py3-none-any.whl (51 kB)
Downloading plotly-6.7.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.9 MB 2.6 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.9 MB 2.9 MB/s eta 0:00:03
   --------- ------------------------------ 2.4/9.9 MB 3.0 MB/s eta 0:00:03
   ----------- ---------------------------- 2.9/9.9 MB 3.1 MB/s eta 0:00:03
   -------------- ------------------------- 3.7/9.9 MB 3.1 MB/s eta 0:00:02
   ---------------- ----------------------- 4.2/9.9 MB 3.1 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.9 MB 3.0 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.9 MB 2.9 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.9 MB 2.9 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.9 MB 2.8 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.9 MB 2.9 MB/s eta 0:00:02
   ------------------------------ --------- 7.6/9.9 MB 2.9 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/9.9 MB 2.9 MB/s eta 0:00:01
   ---------------------------------- ----- 8.7/9.9 MB 2.9 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 2.9 MB/s  0:00:03
Downloading narwhals-2.20.0-py3-none-any.whl (449 kB)
Downloading requests_file-3.0.1-py2.py3-none-any.whl (4.5 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, narwhals, requests-file, plotly, finance-datareader

   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   -------------------------------- ------- 4/5 [finance-datareader]
   -------------------------------- ------- 4/5 [finance-datareader]
   -------------------------------- ------- 4/5 [finance-datareader]
   -------------------------------- ------- 4/5 [finance-datareader]
   ---------------------------------------- 5/5 [finance-datareader]

Successfully installed finance-datareader-0.9.110 narwhals-2.20.0 plotly-6.7.0 requests-file-3.0.1 tqdm-4.67.3

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
stock.get_market_ohlcv_by_ticker('20260422', market='KOSPI')

Error occurred in get_market_ohlcv_by_ticker: Expecting value: line 1 column 1 (char 0)

KeyError: "None of [Index(['시가', '고가', '저가', '종가'], dtype='object')] are in the [columns]"

In [33]:
stock.get_market_fundamental('20250404', '20250405', '005930')

Error occurred in get_market_fundamental_by_date: Expecting value: line 1 column 1 (char 0)

Empty DataFrame
Columns: []
Index: []