### **TF-IDF 벡터화**

- TF(단어 빈도): 특정 문서 안에서 단어가 얼마나 자주 등장하는가?
- IDF(역문서 빈도): 전체 문서들 중 그 단어가 등장한 문서 비율의 역수
- 단순하게 단어의 개수를 세는 방법(CountVectorizer)을 보완하여, 이 문서에서는 유독 자주 나오는데 다른 문서들에서는 잘 안 나오는, 유독 튀는 단어에 가중치를 부여하는 알고리즘
- 수식적으로 표현하면 TF * IDF 로 계산되어 텍스트를 실수형 벡터로 변환

<br>

- 매개변수

    - `stop_words`
        - default: None
        - 불용어 처리
        - 리스트 형태를 통해서 특정 단어들을 제외
        - `english`를 인자로 사용하면 영문자를 제외
    
    - `min_df`
        - default: 1
        - 최소 문서 빈도
        - 정수(개수), 실수(비율)로 설정
        - `min_df` = 3 이면 전체 문서에서 3개 미만의 문서에서 등장하는 단어는 '오타'나 '너무 희귀한 단어'로 간주하여 단어 사전에서 제외
    
    - `max_df`
        - default: 1.0
        - 최대 문서 빈도
        - 너무 자주 등장하는 단어 제외
        - `max_df` = 0.9 로 설정하면 전체 문서에서 90% 이상 등장하는 단어는 제외
    
    - `ngram_range`
        - default: (1, 1)
        - 단어의 묶음 단위를 지정
        - (1, 2) 로 설정하게 되면 1개의 단어(unigram) 뿐만이 아니라 2개의 단어 묶음(bigram)도 하나의 feature로 사용 (ex. ('자연어', '처리', '자연어 처리'))
    
    - `lowercase`
        - default: True
        - 영문 텍스트를 학습할 때, 모든 문자를 소문자로 변환할 지의 여부를 결정
    
    - `max_features`
        - default: None
        - 단어 사전에서 단어들의 개수를 지정
        - 중요도(빈도) 기준 상위 n개의 키워드만 사용

In [2]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
news_docs = [
    '한국은행 기준 금리 인상 발표 기자 무단전재',
    '미국 연준 금리 인상 가능성 시사 기자 무단전재',
    '한국은행 기준 금리 동결 결정 경제 전망 기자 무단전재',
    '주식 시장 하락 금리 인상 여파 기자',
    '딥러닝 기반 자연어 처리 금리 예측 모델 개발'
]

In [14]:
# 불용어 처리
stop_words = ['기자', '무단전재']

tfidf_vec = TfidfVectorizer(
    stop_words = stop_words,
    ngram_range = (1, 3),
    min_df = 1,
    max_df = 1.0,
    lowercase = False,
    max_features = 20
)

In [15]:
tfidf_matrix = tfidf_vec.fit_transform(news_docs)

In [16]:
# 학습된 단어 사전을 가져오기 → 데이터프레임의 피쳐로 사용

feature_names = tfidf_vec.get_feature_names_out()
feature_names

array(['가능성', '결정 경제', '결정 경제 전망', '경제', '경제 전망', '금리', '금리 동결',
       '금리 동결 결정', '금리 예측', '금리 인상', '금리 인상 가능성', '금리 인상 발표', '금리 인상 여파',
       '기반', '기준', '기준 금리', '인상', '한국은행', '한국은행 기준', '한국은행 기준 금리'],
      dtype=object)

In [17]:
df = pd.DataFrame(tfidf_matrix.toarray(), columns = feature_names)
df

,가능성,결정 경제,결정 경제 전망,경제,경제 전망,금리,금리 동결,금리 동결 결정,금리 예측,금리 인상,금리 인상 가능성,금리 인상 발표,금리 인상 여파,기반,기준,기준 금리,인상,한국은행,한국은행 기준,한국은행 기준 금리
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.205462,0.000000,0.000000,0.000000,0.288769,0.000000,0.431184,0.000000,0.000000,0.347877,0.347877,0.288769,0.347877,0.347877,0.347877
1,0.565768,0.000000,0.000000,0.000000,0.000000,0.269592,0.000000,0.000000,0.000000,0.378902,0.565768,0.000000,0.000000,0.000000,0.000000,0.000000,0.378902,0.000000,0.000000,0.000000
2,0.000000,0.324757,0.324757,0.324757,0.324757,0.154748,0.324757,0.324757,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.262012,0.262012,0.000000,0.262012,0.262012,0.262012
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.326950,0.000000,0.000000,0.000000,0.459517,0.000000,0.000000,0.686142,0.000000,0.000000,0.000000,0.459517,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.319302,0.000000,0.000000,0.670092,0.000000,0.000000,0.000000,0.000000,0.670092,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [18]:
# 벡터화 + 토큰화
# 토큰화 komoran

from konlpy.tag import Komoran

In [28]:
# komoran class 생성
komoran = Komoran()

# 토큰화 함수 생성
def tokenize(text):
    # 사용할 품사 지정
    allow_pos = ['NNP', 'NNG', 'VV', 'VA', 'SL', 'MAG']
    stop_words = ['기자', '무단', '전재']
    # 글자 수 제한
    len_word = 2

    result = []

    for word, pos in komoran.pos(text):
        if (pos in allow_pos) & (word not in stop_words) & (len(word) >= len_word):
            result.append(word)
    
    return result

In [29]:
tfidf_vec2 = TfidfVectorizer(
    tokenizer = tokenize,
    min_df = 1,
    max_df = 0.9,
    ngram_range = (1, 1),
    max_features = 20
)

In [30]:
tfidf_matrix2 = tfidf_vec2.fit_transform(news_docs)
feature_names2 = tfidf_vec2.get_feature_names_out()
df2 = pd.DataFrame(tfidf_matrix2.toarray(), columns = feature_names2)
df2

c:\Users\hkssn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

,개발,결정,경제,기반,기준,동결,모델,미국,발표,시사,여파,연준,예측,인상,자연어,전망,주식 시장,처리,하락,한국은행
0,0.000000,0.000000,0.000000,0.000000,0.486484,0.000000,0.000000,0.000000,0.602985,0.000000,0.000000,0.000000,0.000000,0.403826,0.000000,0.000000,0.000000,0.000000,0.000000,0.486484
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.538498,0.000000,0.538498,0.000000,0.538498,0.000000,0.360638,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.434297,0.434297,0.000000,0.350388,0.434297,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.434297,0.000000,0.000000,0.000000,0.350388
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.538498,0.000000,0.000000,0.360638,0.000000,0.000000,0.538498,0.000000,0.538498,0.000000
4,0.408248,0.000000,0.000000,0.408248,0.000000,0.000000,0.408248,0.000000,0.000000,0.000000,0.000000,0.000000,0.408248,0.000000,0.408248,0.000000,0.000000,0.408248,0.000000,0.000000