In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup as bs

In [4]:
dfs = pd.read_html("https://comp.wisereport.co.kr/company/c1010001.aspx?cmp_cd=000120", encoding='cp949')

In [5]:
dfs[3]

                          0                                     1
0               주가/전일대비/수익률            107,200원 /  +400원 / +0.38%
1             52Weeks 최고/최저                   154,000원 /  77,400원
2                       액면가                                5,000원
3                  거래량/거래대금                       51,712주 /  56억원
4                      시가총액                              24,455억원
5                     52주베타                                  0.64
6              발행주식수/유동주식비율                  22,812,344주 / 47.24%
7                    외국인지분율                                17.92%
8   수익률 (1M / 3M / 6M / 1Y)  -5.80% / +10.63% / +30.89% / +28.38%
9                  주가 (NXT)                              107,800원
10           거래량/거래대금 (NXT)                       25,941주 /  28억원

In [6]:
dfs[2]

,0,1
0,CJ대한통운 000120 홈페이지 대표전화 주소,"EPS10,612 BPS207,860 PER10.10 업종PER13.78 P..."
1,KOSPI : 코스피 운송·창고 | WI26 : 운송 | 12월 결산 | K2...,"EPS10,612 BPS207,860 PER10.10 업종PER13.78 P..."

In [11]:
dfs[2][0][0][0:6]

'CJ대한통운'

In [12]:
# 특정 종목 5개의 데이터를 크롤링: 005930, 009150, 000660, 080220, 096770
# 크롤링에서 반복문을 이용해서 사이트에 접속할 때는 딜레이 기능을 부여해야 함
import time

In [17]:
# 현재 시간 로드
from datetime import datetime

In [22]:
print(datetime.today())
print(datetime.now())

print(datetime.now().strftime('%y%m%d'))
now_str = datetime.now().strftime('%y%m%d')

2026-04-21 17:21:41.707847
2026-04-21 17:21:41.708195
260421

In [ ]:
code_list = ['005930', '009150', '000660', '080220', '096770']
now_str = datetime.now().strftime('%y%m%d')

for code in code_list:
    base_url = 'https://comp.wisereport.co.kr/company/c1010001.aspx?cmp_cd='
    df = pd.read_html(base_url+code, encoding='cp949')[3]
    df.to_csv(f"./{code} {now_str}.csv")

    # 시간의 딜레이
    time.sleep(1)

In [ ]:
code_list = []
# 반복문을 생성하는데 반복 횟수는 명확하지 않다.
while True:
    input_code = input('종목 코드 6자리를 입력하시오. (입력값 종료 시 ENTER)')
    if len(input_code) == 6:
        code_list.append(input_code)
    
    # input_code가 존재하지 않는다면
    if not(bool(input_code)):
        break


now_str = datetime.now().strftime('%y%m%d')

for code in code_list:
    base_url = 'https://comp.wisereport.co.kr/company/c1010001.aspx?cmp_cd='
    df = pd.read_html(base_url+code, encoding='cp949')[3]
    df.to_csv(f"./{code} {now_str}.csv")

    # 시간의 딜레이
    time.sleep(1)