#### 문제
- pandas를 이용해서 data 폴더 안 'rating_train.txt' 파일 로드
- 결측치, 중복값 제거
- 상위 500개 데이터 필터링
- document 데이터와 label 데이터로 나눠준다. (독립/종속)
- embed 라이브러리 이용하여 토큰화, 벡터화 작업
- 분류 모델은 svc, logistic 모델 이용 (parameter defalut)
- 벡터화 방법 2가지를 이용하고 모델 2개를 이용하여 성능 평가
- 최적의 모델을 이용하여 하위 200개의 데이터를 예측하고 분류 레포트 생성

In [1]:
import pandas as pd

df = pd.read_csv('../data/ratings_train.txt', sep='\t')
df.head()

         id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [2]:
df.drop('id', axis = 1, inplace = True)

In [3]:
df.dropna(inplace=True)

In [4]:
df.drop_duplicates('document', inplace=True)

In [5]:
X = df['document'][:500].values
y = df['label'][:500].values

In [6]:
X

<StringArray>
[                                                                                                         '아 더빙.. 진짜 짜증나네요 목소리',
                                                                                            '흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나',
                                                                                                            '너무재밓었다그래서보는것을추천한다',
                                                                                                '교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정',
                                                                '사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 던스트가 너무나도 이뻐보였다',
                                                                                '막 걸음마 뗀 3세부터 초등학교 1학년생인 8살용영화.ㅋㅋㅋ...별반개도 아까움.',
                                                                                                        '원작의 긴장감을 제대로 살려내지못했다.',
                                       '별 반개도 아깝다 욕나온다 이응경 길용우 연기생활이몇년인지..정말 발로해도 그것보단 낫겟다 납치.감금만반복반복..이드라마는 가족도없다 연기못하는사람만모엿네',
                                                                                                       '액션이 없는데도 재미 있는 몇안되는 영화',
                                                                                '왜케 평점이 낮은건데? 꽤 볼만한데.. 헐리우드식 화려함에만 너무 길들여져 있나?',
 ...
 '막장도 재미가있어야 보지..재미도 없고 짜증만 남남녀주인공이 어울리면 참고보겠는데 진짜 안어울리고웬만하면 다 재밌게 보는데 진짜 내가본것중 제일 최악이였음!!무튼 주인공들부터시작해서 성격 개 이상함!!조기종영이 답이다...',
                                                                                                           '줄리델피는 나이가 들수록 멋지다!',
                                                                                                        '내가 본 일드 중 쵝오~!!!!!>0<',
                                                                                                               '역시 명작은 명작이다...',
                                                                                   '글쎄요.... 뭐랄까... 영화 제목을 잘못 보고 착각한 내 잘못이랄까...',
                                                                        '그냥 기독교영화네요. 좀 더 깊이있는 내용을 기대했는데.. 실망입니다. 영화도 뭔가 엉성해요;;',
                                        '그냥 책으로 읽는게 더 절절하게 다가온다. 영화는 내용을 너무 비약하고 삭제해서 행간을 잃어버렸다. 책에서 꽉 찼었던 느낌과 반대로 모든 것이 엉성하다.',
                                                                                                                  '너무나 감동적인 영화',
                                                                                                        '스킨헤드성님들이 이 영화를 싫어합니다.',
                                                                                              '자동차 매니아인 나의 평점은 5점 이하~속았다...아오~']
Length: 500, dtype: str

In [7]:
y

array([0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0])

In [8]:
import embed

In [9]:
tokens = embed.global_vari_set(X)

c:\Users\hkssn\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\feature_extraction\text.py:527: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import classification_report

logi_wv = LogisticRegression(random_state = 42)
logi_idf = LogisticRegression(random_state = 42)
svc_wv = SVC(random_state = 42)
svc_idf = SVC(random_state = 42)

In [11]:
X_wv = []
X_idf = []

for token in tokens:
    vec_wv = embed.sent_embed_mean(token)
    vec_idf = embed.sent_embed_wv_idf(token)
    X_wv.append(vec_wv)
    X_idf.append(vec_idf)

In [12]:
print(embed.run_model(X_wv, y, model = logi_wv))
print(embed.run_model(X_idf, y, model = logi_idf))

              precision    recall  f1-score   support

           0       0.61      0.62      0.61        50
           1       0.61      0.60      0.61        50

    accuracy                           0.61       100
   macro avg       0.61      0.61      0.61       100
weighted avg       0.61      0.61      0.61       100

None
              precision    recall  f1-score   support

           0       0.61      0.60      0.61        50
           1       0.61      0.62      0.61        50

    accuracy                           0.61       100
   macro avg       0.61      0.61      0.61       100
weighted avg       0.61      0.61      0.61       100

None

In [13]:
print(embed.run_model(X_wv, y, model = svc_wv))
print(embed.run_model(X_idf, y, model = svc_idf))

              precision    recall  f1-score   support

           0       0.64      0.64      0.64        50
           1       0.64      0.64      0.64        50

    accuracy                           0.64       100
   macro avg       0.64      0.64      0.64       100
weighted avg       0.64      0.64      0.64       100

None
              precision    recall  f1-score   support

           0       0.64      0.64      0.64        50
           1       0.64      0.64      0.64        50

    accuracy                           0.64       100
   macro avg       0.64      0.64      0.64       100
weighted avg       0.64      0.64      0.64       100

None

In [15]:
# 최적의 모델(svc_idf)을 이용하여 예측

X_test = df['document'].tail(100).values
y_test = df['label'].tail(100).values

In [16]:
pred = embed.predict_sentence_list(X_test, svc_idf, 'idf')

In [17]:
pred_df = pd.DataFrame(pred, columns = ['sentence', 'label'])
pred_df

                                             sentence label
0                    여운이길다..배우들의연기가 대단하다 쿼어영화중에최고같다..    긍정
1                                               연기 끝장    긍정
2   "용재오닐이 아이들에게"" 너의선택이아니야~너의 잘못이 아니야!!""라고 할때 눈물...    긍정
3                   제작사와감독에게할복을요청하고싶다...일본영화의 최대망작!!!    부정
4       나는 조르쥬와 다른가를 생각해보면 소름이 끼친다. 오랫만에 나를 궁지로 내몬 영화    부정
..                                                ...   ...
95                                인간이 문제지.. 소는 뭔죄인가..    부정
96                                      평점이 너무 낮아서...    부정
97                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?    부정
98                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상    부정
99                           한국 영화 최초로 수간하는 내용이 담긴 영화    부정

[100 rows x 2 columns]

In [18]:
pred_y = pred_df['label'].map({
    '부정': 0,
    '긍정': 1
})

In [21]:
pred_y

0     1
1     1
2     1
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Name: label, Length: 100, dtype: int64

In [22]:
print(classification_report(y_test, pred_y.values))

              precision    recall  f1-score   support

           0       0.59      0.74      0.66        47
           1       0.71      0.55      0.62        53

    accuracy                           0.64       100
   macro avg       0.65      0.65      0.64       100
weighted avg       0.65      0.64      0.64       100