In [1]:
import pandas as pd
import requests
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import platform

from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import MinMaxScaler

In [63]:
url = "https://archive-api.open-meteo.com/v1/archive"

params = {
    'latitude': 37.5665,
    'longitude': 126.9780,
    'start_date': '2025-01-01',
    'end_date': '2025-12-31',
    'hourly': 'temperature_2m,relative_humidity_2m,surface_pressure,wind_speed_10m,rain'
}

res = requests.get(url, params = params)
data = res.json()
data

{'latitude': 37.57469,
 'longitude': 126.96,
 'generationtime_ms': 113.43216896057129,
 'utc_offset_seconds': 0,
 'timezone': 'GMT',
 'timezone_abbreviation': 'GMT',
 'elevation': 34.0,
 'hourly_units': {'time': 'iso8601',
  'temperature_2m': '°C',
  'relative_humidity_2m': '%',
  'surface_pressure': 'hPa',
  'wind_speed_10m': 'km/h',
  'rain': 'mm'},
 'hourly': {'time': ['2025-01-01T00:00',
   '2025-01-01T01:00',
   '2025-01-01T02:00',
   '2025-01-01T03:00',
   '2025-01-01T04:00',
   '2025-01-01T05:00',
   '2025-01-01T06:00',
   '2025-01-01T07:00',
   '2025-01-01T08:00',
   '2025-01-01T09:00',
   '2025-01-01T10:00',
   '2025-01-01T11:00',
   '2025-01-01T12:00',
   '2025-01-01T13:00',
   '2025-01-01T14:00',
   '2025-01-01T15:00',
   '2025-01-01T16:00',
   '2025-01-01T17:00',
   '2025-01-01T18:00',
   '2025-01-01T19:00',
   '2025-01-01T20:00',
   '2025-01-01T21:00',
   '2025-01-01T22:00',
   '2025-01-01T23:00',
   '2025-01-02T00:00',
   '2025-01-02T01:00',
   '2025-01-02T02:00',
   '2025-01-02T03:00',
   '2025-01-02T04:00',
   '2025-01-02T05:00',
   '2025-01-02T06:00',
   '2025-01-02T07:00',
   '2025-01-02T08:00',
   '2025-01-02T09:00',
   '2025-01-02T10:00',
   '2025-01-02T11:00',
   '2025-01-02T12:00',
   '2025-01-02T13:00',
   '2025-01-02T14:00',
   '2025-01-02T15:00',
   '2025-01-02T16:00',
   '2025-01-02T17:00',
   '2025-01-02T18:00',
   '2025-01-02T19:00',
   '2025-01-02T20:00',
   '2025-01-02T21:00',
   '2025-01-02T22:00',
   '2025-01-02T23:00',
   '2025-01-03T00:00',
   '2025-01-03T01:00',
   '2025-01-03T02:00',
   '2025-01-03T03:00',
   '2025-01-03T04:00',
   '2025-01-03T05:00',
   '2025-01-03T06:00',
   '2025-01-03T07:00',
   '2025-01-03T08:00',
   '2025-01-03T09:00',
   '2025-01-03T10:00',
   '2025-01-03T11:00',
   '2025-01-03T12:00',
   '2025-01-03T13:00',
   '2025-01-03T14:00',
   '2025-01-03T15:00',
   '2025-01-03T16:00',
   '2025-01-03T17:00',
   '2025-01-03T18:00',
   '2025-01-03T19:00',
   '2025-01-03T20:00',
   '2025-01-03T21:00',
   '2025-01-03T22:00',
   '2025-01-03T23:00',
   '2025-01-04T00:00',
   '2025-01-04T01:00',
   '2025-01-04T02:00',
   '2025-01-04T03:00',
   '2025-01-04T04:00',
   '2025-01-04T05:00',
   '2025-01-04T06:00',
   '2025-01-04T07:00',
   '2025-01-04T08:00',
   '2025-01-04T09:00',
   '2025-01-04T10:00',
   '2025-01-04T11:00',
   '2025-01-04T12:00',
   '2025-01-04T13:00',
   '2025-01-04T14:00',
   '2025-01-04T15:00',
   '2025-01-04T16:00',
   '2025-01-04T17:00',
   '2025-01-04T18:00',
   '2025-01-04T19:00',
   '2025-01-04T20:00',
   '2025-01-04T21:00',
   '2025-01-04T22:00',
   '2025-01-04T23:00',
   '2025-01-05T00:00',
   '2025-01-05T01:00',
   '2025-01-05T02:00',
   '2025-01-05T03:00',
   '2025-01-05T04:00',
   '2025-01-05T05:00',
   '2025-01-05T06:00',
   '2025-01-05T07:00',
   '2025-01-05T08:00',
   '2025-01-05T09:00',
   '2025-01-05T10:00',
   '2025-01-05T11:00',
   '2025-01-05T12:00',
   '2025-01-05T13:00',
   '2025-01-05T14:00',
   '2025-01-05T15:00',
   '2025-01-05T16:00',
   '2025-01-05T17:00',
   '2025-01-05T18:00',
   '2025-01-05T19:00',
   '2025-01-05T20:00',
   '2025-01-05T21:00',
   '2025-01-05T22:00',
   '2025-01-05T23:00',
   '2025-01-06T00:00',
   '2025-01-06T01:00',
   '2025-01-06T02:00',
   '2025-01-06T03:00',
   '2025-01-06T04:00',
   '2025-01-06T05:00',
   '2025-01-06T06:00',
   '2025-01-06T07:00',
   '2025-01-06T08:00',
   '2025-01-06T09:00',
   '2025-01-06T10:00',
   '2025-01-06T11:00',
   '2025-01-06T12:00',
   '2025-01-06T13:00',
   '2025-01-06T14:00',
   '2025-01-06T15:00',
   '2025-01-06T16:00',
   '2025-01-06T17:00',
   '2025-01-06T18:00',
   '2025-01-06T19:00',
   '2025-01-06T20:00',
   '2025-01-06T21:00',
   '2025-01-06T22:00',
   '2025-01-06T23:00',
   '2025-01-07T00:00',
   '2025-01-07T01:00',
   '2025-01-07T02:00',
   '2025-01-07T03:00',
   '2025-01-07T04:00',
   '2025-01-07T05:00',
   '2025-01-07T06:00',
   '2025-01-07T07:00',
   '2025-01-07T08:00',
   '2025-01-07T09:00',
   '2025-01-07T10:00',
   '2025-01-07T11:00',
   '2025-01-07T12:00',
   '2025-01-07T13:00',
   '2025-01-07T14:00',
   '2025-01-07T15:00',
   '2025-01-07T16:00',
   '2025-01-07T17:00',
   '2025-01-07T18:00',
   '2025-01-07T19:00',
   '2025-01-07T20:00',
   '2025-01-07T21:00',
   '2025-01-07T22:00',
   '2025-01-07T23:00',
   '2025-01-08T00:00',
   '2025-01-08T01:00',
   '2025-01-08T02:00',
   '2025-01-08T03:00',
   '2025-01-08T04:00',
   '2025-01-08T05:00',
   '2025-01-08T06:00',
   '2025-01-08T07:00',
   '2025-01-08T08:00',
   '2025-01-08T09:00',
   '2025-01-08T10:00',
   '2025-01-08T11:00',
   '2025-01-08T12:00',
   '2025-01-08T13:00',
   '2025-01-08T14:00',
   '2025-01-08T15:00',
   '2025-01-08T16:00',
   '2025-01-08T17:00',
   '2025-01-08T18:00',
   '2025-01-08T19:00',
   '2025-01-08T20:00',
   '2025-01-08T21:00',
   '2025-01-08T22:00',
   '2025-01-08T23:00',
   '2025-01-09T00:00',
   '2025-01-09T01:00',
   '2025-01-09T02:00',
   '2025-01-09T03:00',
   '2025-01-09T04:00',
   '2025-01-09T05:00',
   '2025-01-09T06:00',
   '2025-01-09T07:00',
   '2025-01-09T08:00',
   '2025-01-09T09:00',
   '2025-01-09T10:00',
   '2025-01-09T11:00',
   '2025-01-09T12:00',
   '2025-01-09T13:00',
   '2025-01-09T14:00',
   '2025-01-09T15:00',
   '2025-01-09T16:00',
   '2025-01-09T17:00',
   '2025-01-09T18:00',
   '2025-01-09T19:00',
   '2025-01-09T20:00',
   '2025-01-09T21:00',
   '2025-01-09T22:00',
   '2025-01-09T23:00',
   '2025-01-10T00:00',
   '2025-01-10T01:00',
   '2025-01-10T02:00',
   '2025-01-10T03:00',
   '2025-01-10T04:00',
   '2025-01-10T05:00',
   '2025-01-10T06:00',
   '2025-01-10T07:00',
   '2025-01-10T08:00',
   '2025-01-10T09:00',
   '2025-01-10T10:00',
   '2025-01-10T11:00',
   '2025-01-10T12:00',
   '2025-01-10T13:00',
   '2025-01-10T14:00',
   '2025-01-10T15:00',
   '2025-01-10T16:00',
   '2025-01-10T17:00',
   '2025-01-10T18:00',
   '2025-01-10T19:00',
   '2025-01-10T20:00',
   '2025-01-10T21:00',
   '2025-01-10T22:00',
   '2025-01-10T23:00',
   '2025-01-11T00:00',
   '2025-01-11T01:00',
   '2025-01-11T02:00',
   '2025-01-11T03:00',
   '2025-01-11T04:00',
   '2025-01-11T05:00',
   '2025-01-11T06:00',
   '2025-01-11T07:00',
   '2025-01-11T08:00',
   '2025-01-11T09:00',
   '2025-01-11T10:00',
   '2025-01-11T11:00',
   '2025-01-11T12:00',
   '2025-01-11T13:00',
   '2025-01-11T14:00',
   '2025-01-11T15:00',
   '2025-01-11T16:00',
   '2025-01-11T17:00',
   '2025-01-11T18:00',
   '2025-01-11T19:00',
   '2025-01-11T20:00',
   '2025-01-11T21:00',
   '2025-01-11T22:00',
   '2025-01-11T23:00',
   '2025-01-12T00:00',
   '2025-01-12T01:00',
   '2025-01-12T02:00',
   '2025-01-12T03:00',
   '2025-01-12T04:00',
   '2025-01-12T05:00',
   '2025-01-12T06:00',
   '2025-01-12T07:00',
   '2025-01-12T08:00',
   '2025-01-12T09:00',
   '2025-01-12T10:00',
   '2025-01-12T11:00',
   '2025-01-12T12:00',
   '2025-01-12T13:00',
   '2025-01-12T14:00',
   '2025-01-12T15:00',
   '2025-01-12T16:00',
   '2025-01-12T17:00',
   '2025-01-12T18:00',
   '2025-01-12T19:00',
   '2025-01-12T20:00',
   '2025-01-12T21:00',
   '2025-01-12T22:00',
   '2025-01-12T23:00',
   '2025-01-13T00:00',
   '2025-01-13T01:00',
   '2025-01-13T02:00',
   '2025-01-13T03:00',
   '2025-01-13T04:00',
   '2025-01-13T05:00',
   '2025-01-13T06:00',
   '2025-01-13T07:00',
   '2025-01-13T08:00',
   '2025-01-13T09:00',
   '2025-01-13T10:00',
   '2025-01-13T11:00',
   '2025-01-13T12:00',
   '2025-01-13T13:00',
   '2025-01-13T14:00',
   '2025-01-13T15:00',
   '2025-01-13T16:00',
   '2025-01-13T17:00',
   '2025-01-13T18:00',
   '2025-01-13T19:00',
   '2025-01-13T20:00',
   '2025-01-13T21:00',
   '2025-01-13T22:00',
   '2025-01-13T23:00',
   '2025-01-14T00:00',
   '2025-01-14T01:00',
   '2025-01-14T02:00',
   '2025-01-14T03:00',
   '2025-01-14T04:00',
   '2025-01-14T05:00',
   '2025-01-14T06:00',
   '2025-01-14T07:00',
   '2025-01-14T08:00',
   '2025-01-14T09:00',
   '2025-01-14T10:00',
   '2025-01-14T11:00',
   '2025-01-14T12:00',
   '2025-01-14T13:00',
   '2025-01-14T14:00',
   '2025-01-14T15:00',
   '2025-01-14T16:00',
   '2025-01-14T17:00',
   '2025-01-14T18:00',
   '2025-01-14T19:00',
   '2025-01-14T20:00',
   '2025-01-14T21:00',
   '2025-01-14T22:00',
   '2025-01-14T23:00',
   '2025-01-15T00:00',
   '2025-01-15T01:00',
   '2025-01-15T02:00',
   '2025-01-15T03:00',
   '2025-01-15T04:00',
   '2025-01-15T05:00',
   '2025-01-15T06:00',
   '2025-01-15T07:00',
   '2025-01-15T08:00',
   '2025-01-15T09:00',
   '2025-01-15T10:00',
   '2025-01-15T11:00',
   '2025-01-15T12:00',
   '2025-01-15T13:00',
   '2025-01-15T14:00',
   '2025-01-15T15:00',
   '2025-01-15T16:00',
   '2025-01-15T17:00',
   '2025-01-15T18:00',
   '2025-01-15T19:00',
   '2025-01-15T20:00',
   '2025-01-15T21:00',
   '2025-01-15T22:00',
   '2025-01-15T23:00',
   '2025-01-16T00:00',
   '2025-01-16T01:00',
   '2025-01-16T02:00',
   '2025-01-16T03:00',
   '2025-01-16T04:00',
   '2025-01-16T05:00',
   '2025-01-16T06:00',
   '2025-01-16T07:00',
   '2025-01-16T08:00',
   '2025-01-16T09:00',
   '2025-01-16T10:00',
   '2025-01-16T11:00',
   '2025-01-16T12:00',
   '2025-01-16T13:00',
   '2025-01-16T14:00',
   '2025-01-16T15:00',
   '2025-01-16T16:00',
   '2025-01-16T17:00',
   '2025-01-16T18:00',
   '2025-01-16T19:00',
   '2025-01-16T20:00',
   '2025-01-16T21:00',
   '2025-01-16T22:00',
   '2025-01-16T23:00',
   '2025-01-17T00:00',
   '2025-01-17T01:00',
   '2025-01-17T02:00',
   '2025-01-17T03:00',
   '2025-01-17T04:00',
   '2025-01-17T05:00',
   '2025-01-17T06:00',
   '2025-01-17T07:00',
   '2025-01-17T08:00',
   '2025-01-17T09:00',
   '2025-01-17T10:00',
   '2025-01-17T11:00',
   '2025-01-17T12:00',
   '2025-01-17T13:00',
   '2025-01-17T14:00',
   '2025-01-17T15:00',
   '2025-01-17T16:00',
   '2025-01-17T17:00',
   '2025-01-17T18:00',
   '2025-01-17T19:00',
   '2025-01-17T20:00',
   '2025-01-17T21:00',
   '2025-01-17T22:00',
   '2025-01-17T23:00',
   '2025-01-18T00:00',
   '2025-01-18T01:00',
   '2025-01-18T02:00',
   '2025-01-18T03:00',
   '2025-01-18T04:00',
   '2025-01-18T05:00',
   '2025-01-18T06:00',
   '2025-01-18T07:00',
   '2025-01-18T08:00',
   '2025-01-18T09:00',
   '2025-01-18T10:00',
   '2025-01-18T11:00',
   '2025-01-18T12:00',
   '2025-01-18T13:00',
   '2025-01-18T14:00',
   '2025-01-18T15:00',
   '2025-01-18T16:00',
   '2025-01-18T17:00',
   '2025-01-18T18:00',
   '2025-01-18T19:00',
   '2025-01-18T20:00',
   '2025-01-18T21:00',
   '2025-01-18T22:00',
   '2025-01-18T23:00',
   '2025-01-19T00:00',
   '2025-01-19T01:00',
   '2025-01-19T02:00',
   '2025-01-19T03:00',
   '2025-01-19T04:00',
   '2025-01-19T05:00',
   '2025-01-19T06:00',
   '2025-01-19T07:00',
   '2025-01-19T08:00',
   '2025-01-19T09:00',
   '2025-01-19T10:00',
   '2025-01-19T11:00',
   '2025-01-19T12:00',
   '2025-01-19T13:00',
   '2025-01-19T14:00',
   '2025-01-19T15:00',
   '2025-01-19T16:00',
   '2025-01-19T17:00',
   '2025-01-19T18:00',
   '2025-01-19T19:00',
   '2025-01-19T20:00',
   '2025-01-19T21:00',
   '2025-01-19T22:00',
   '2025-01-19T23:00',
   '2025-01-20T00:00',
   '2025-01-20T01:00',
   '2025-01-20T02:00',
   '2025-01-20T03:00',
   '2025-01-20T04:00',
   '2025-01-20T05:00',
   '2025-01-20T06:00',
   '2025-01-20T07:00',
   '2025-01-20T08:00',
   '2025-01-20T09:00',
   '2025-01-20T10:00',
   '2025-01-20T11:00',
   '2025-01-20T12:00',
   '2025-01-20T13:00',
   '2025-01-20T14:00',
   '2025-01-20T15:00',
   '2025-01-20T16:00',
   '2025-01-20T17:00',
   '2025-01-20T18:00',
   '2025-01-20T19:00',
   '2025-01-20T20:00',
   '2025-01-20T21:00',
   '2025-01-20T22:00',
   '2025-01-20T23:00',
   '2025-01-21T00:00',
   '2025-01-21T01:00',
   '2025-01-21T02:00',
   '2025-01-21T03:00',
   '2025-01-21T04:00',
   '2025-01-21T05:00',
   '2025-01-21T06:00',
   '2025-01-21T07:00',
   '2025-01-21T08:00',
   '2025-01-21T09:00',
   '2025-01-21T10:00',
   '2025-01-21T11:00',
   '2025-01-21T12:00',
   '2025-01-21T13:00',
   '2025-01-21T14:00',
   '2025-01-21T15:00',
   '2025-01-21T16:00',
   '2025-01-21T17:00',
   '2025-01-21T18:00',
   '2025-01-21T19:00',
   '2025-01-21T20:00',
   '2025-01-21T21:00',
   '2025-01-21T22:00',
   '2025-01-21T23:00',
   '2025-01-22T00:00',
   '2025-01-22T01:00',
   '2025-01-22T02:00',
   '2025-01-22T03:00',
   '2025-01-22T04:00',
   '2025-01-22T05:00',
   '2025-01-22T06:00',
   '2025-01-22T07:00',
   '2025-01-22T08:00',
   '2025-01-22T09:00',
   '2025-01-22T10:00',
   '2025-01-22T11:00',
   '2025-01-22T12:00',
   '2025-01-22T13:00',
   '2025-01-22T14:00',
   '2025-01-22T15:00',
   '2025-01-22T16:00',
   '2025-01-22T17:00',
   '2025-01-22T18:00',
   '2025-01-22T19:00',
   '2025-01-22T20:00',
   '2025-01-22T21:00',
   '2025-01-22T22:00',
   '2025-01-22T23:00',
   '2025-01-23T00:00',
   '2025-01-23T01:00',
   '2025-01-23T02:00',
   '2025-01-23T03:00',
   '2025-01-23T04:00',
   '2025-01-23T05:00',
   '2025-01-23T06:00',
   '2025-01-23T07:00',
   '2025-01-23T08:00',
   '2025-01-23T09:00',
   '2025-01-23T10:00',
   '2025-01-23T11:00',
   '2025-01-23T12:00',
   '2025-01-23T13:00',
   '2025-01-23T14:00',
   '2025-01-23T15:00',
   '2025-01-23T16:00',
   '2025-01-23T17:00',
   '2025-01-23T18:00',
   '2025-01-23T19:00',
   '2025-01-23T20:00',
   '2025-01-23T21:00',
   '2025-01-23T22:00',
   '2025-01-23T23:00',
   '2025-01-24T00:00',
   '2025-01-24T01:00',
   '2025-01-24T02:00',
   '2025-01-24T03:00',
   '2025-01-24T04:00',
   '2025-01-24T05:00',
   '2025-01-24T06:00',
   '2025-01-24T07:00',
   '2025-01-24T08:00',
   '2025-01-24T09:00',
   '2025-01-24T10:00',
   '2025-01-24T11:00',
   '2025-01-24T12:00',
   '2025-01-24T13:00',
   '2025-01-24T14:00',
   '2025-01-24T15:00',
   '2025-01-24T16:00',
   '2025-01-24T17:00',
   '2025-01-24T18:00',
   '2025-01-24T19:00',
   '2025-01-24T20:00',
   '2025-01-24T21:00',
   '2025-01-24T22:00',
   '2025-01-24T23:00',
   '2025-01-25T00:00',
   '2025-01-25T01:00',
   '2025-01-25T02:00',
   '2025-01-25T03:00',
   '2025-01-25T04:00',
   '2025-01-25T05:00',
   '2025-01-25T06:00',
   '2025-01-25T07:00',
   '2025-01-25T08:00',
   '2025-01-25T09:00',
   '2025-01-25T10:00',
   '2025-01-25T11:00',
   '2025-01-25T12:00',
   '2025-01-25T13:00',
   '2025-01-25T14:00',
   '2025-01-25T15:00',
   '2025-01-25T16:00',
   '2025-01-25T17:00',
   '2025-01-25T18:00',
   '2025-01-25T19:00',
   '2025-01-25T20:00',
   '2025-01-25T21:00',
   '2025-01-25T22:00',
   '2025-01-25T23:00',
   '2025-01-26T00:00',
   '2025-01-26T01:00',
   '2025-01-26T02:00',
   '2025-01-26T03:00',
   '2025-01-26T04:00',
   '2025-01-26T05:00',
   '2025-01-26T06:00',
   '2025-01-26T07:00',
   '2025-01-26T08:00',
   '2025-01-26T09:00',
   '2025-01-26T10:00',
   '2025-01-26T11:00',
   '2025-01-26T12:00',
   '2025-01-26T13:00',
   '2025-01-26T14:00',
   '2025-01-26T15:00',
   '2025-01-26T16:00',
   '2025-01-26T17:00',
   '2025-01-26T18:00',
   '2025-01-26T19:00',
   '2025-01-26T20:00',
   '2025-01-26T21:00',
   '2025-01-26T22:00',
   '2025-01-26T23:00',
   '2025-01-27T00:00',
   '2025-01-27T01:00',
   '2025-01-27T02:00',
   '2025-01-27T03:00',
   '2025-01-27T04:00',
   '2025-01-27T05:00',
   '2025-01-27T06:00',
   '2025-01-27T07:00',
   '2025-01-27T08:00',
   '2025-01-27T09:00',
   '2025-01-27T10:00',
   '2025-01-27T11:00',
   '2025-01-27T12:00',
   '2025-01-27T13:00',
   '2025-01-27T14:00',
   '2025-01-27T15:00',
   '2025-01-27T16:00',
   '2025-01-27T17:00',
   '2025-01-27T18:00',
   '2025-01-27T19:00',
   '2025-01-27T20:00',
   '2025-01-27T21:00',
   '2025-01-27T22:00',
   '2025-01-27T23:00',
   '2025-01-28T00:00',
   '2025-01-28T01:00',
   '2025-01-28T02:00',
   '2025-01-28T03:00',
   '2025-01-28T04:00',
   '2025-01-28T05:00',
   '2025-01-28T06:00',
   '2025-01-28T07:00',
   '2025-01-28T08:00',
   '2025-01-28T09:00',
   '2025-01-28T10:00',
   '2025-01-28T11:00',
   '2025-01-28T12:00',
   '2025-01-28T13:00',
   '2025-01-28T14:00',
   '2025-01-28T15:00',
   '2025-01-28T16:00',
   '2025-01-28T17:00',
   '2025-01-28T18:00',
   '2025-01-28T19:00',
   '2025-01-28T20:00',
   '2025-01-28T21:00',
   '2025-01-28T22:00',
   '2025-01-28T23:00',
   '2025-01-29T00:00',
   '2025-01-29T01:00',
   '2025-01-29T02:00',
   '2025-01-29T03:00',
   '2025-01-29T04:00',
   '2025-01-29T05:00',
   '2025-01-29T06:00',
   '2025-01-29T07:00',
   '2025-01-29T08:00',
   '2025-01-29T09:00',
   '2025-01-29T10:00',
   '2025-01-29T11:00',
   '2025-01-29T12:00',
   '2025-01-29T13:00',
   '2025-01-29T14:00',
   '2025-01-29T15:00',
   '2025-01-29T16:00',
   '2025-01-29T17:00',
   '2025-01-29T18:00',
   '2025-01-29T19:00',
   '2025-01-29T20:00',
   '2025-01-29T21:00',
   '2025-01-29T22:00',
   '2025-01-29T23:00',
   '2025-01-30T00:00',
   '2025-01-30T01:00',
   '2025-01-30T02:00',
   '2025-01-30T03:00',
   '2025-01-30T04:00',
   '2025-01-30T05:00',
   '2025-01-30T06:00',
   '2025-01-30T07:00',
   '2025-01-30T08:00',
   '2025-01-30T09:00',
   '2025-01-30T10:00',
   '2025-01-30T11:00',
   '2025-01-30T12:00',
   '2025-01-30T13:00',
   '2025-01-30T14:00',
   '2025-01-30T15:00',
   '2025-01-30T16:00',
   '2025-01-30T17:00',
   '2025-01-30T18:00',
   '2025-01-30T19:00',
   '2025-01-30T20:00',
   '2025-01-30T21:00',
   '2025-01-30T22:00',
   '2025-01-30T23:00',
   '2025-01-31T00:00',
   '2025-01-31T01:00',
   '2025-01-31T02:00',
   '2025-01-31T03:00',
   '2025-01-31T04:00',
   '2025-01-31T05:00',
   '2025-01-31T06:00',
   '2025-01-31T07:00',
   '2025-01-31T08:00',
   '2025-01-31T09:00',
   '2025-01-31T10:00',
   '2025-01-31T11:00',
   '2025-01-31T12:00',
   '2025-01-31T13:00',
   '2025-01-31T14:00',
   '2025-01-31T15:00',
   '2025-01-31T16:00',
   '2025-01-31T17:00',
   '2025-01-31T18:00',
   '2025-01-31T19:00',
   '2025-01-31T20:00',
   '2025-01-31T21:00',
   '2025-01-31T22:00',
   '2025-01-31T23:00',
   '2025-02-01T00:00',
   '2025-02-01T01:00',
   '2025-02-01T02:00',
   '2025-02-01T03:00',
   '2025-02-01T04:00',
   '2025-02-01T05:00',
   '2025-02-01T06:00',
   '2025-02-01T07:00',
   '2025-02-01T08:00',
   '2025-02-01T09:00',
   '2025-02-01T10:00',
   '2025-02-01T11:00',
   '2025-02-01T12:00',
   '2025-02-01T13:00',
   '2025-02-01T14:00',
   '2025-02-01T15:00',
   '2025-02-01T16:00',
   '2025-02-01T17:00',
   '2025-02-01T18:00',
   '2025-02-01T19:00',
   '2025-02-01T20:00',
   '2025-02-01T21:00',
   '2025-02-01T22:00',
   '2025-02-01T23:00',
   '2025-02-02T00:00',
   '2025-02-02T01:00',
   '2025-02-02T02:00',
   '2025-02-02T03:00',
   '2025-02-02T04:00',
   '2025-02-02T05:00',
   '2025-02-02T06:00',
   '2025-02-02T07:00',
   '2025-02-02T08:00',
   '2025-02-02T09:00',
   '2025-02-02T10:00',
   '2025-02-02T11:00',
   '2025-02-02T12:00',
   '2025-02-02T13:00',
   '2025-02-02T14:00',
   '2025-02-02T15:00',
   '2025-02-02T16:00',
   '2025-02-02T17:00',
   '2025-02-02T18:00',
   '2025-02-02T19:00',
   '2025-02-02T20:00',
   '2025-02-02T21:00',
   '2025-02-02T22:00',
   '2025-02-02T23:00',
   '2025-02-03T00:00',
   '2025-02-03T01:00',
   '2025-02-03T02:00',
   '2025-02-03T03:00',
   '2025-02-03T04:00',
   '2025-02-03T05:00',
   '2025-02-03T06:00',
   '2025-02-03T07:00',
   '2025-02-03T08:00',
   '2025-02-03T09:00',
   '2025-02-03T10:00',
   '2025-02-03T11:00',
   '2025-02-03T12:00',
   '2025-02-03T13:00',
   '2025-02-03T14:00',
   '2025-02-03T15:00',
   '2025-02-03T16:00',
   '2025-02-03T17:00',
   '2025-02-03T18:00',
   '2025-02-03T19:00',
   '2025-02-03T20:00',
   '2025-02-03T21:00',
   '2025-02-03T22:00',
   '2025-02-03T23:00',
   '2025-02-04T00:00',
   '2025-02-04T01:00',
   '2025-02-04T02:00',
   '2025-02-04T03:00',
   '2025-02-04T04:00',
   '2025-02-04T05:00',
   '2025-02-04T06:00',
   '2025-02-04T07:00',
   '2025-02-04T08:00',
   '2025-02-04T09:00',
   '2025-02-04T10:00',
   '2025-02-04T11:00',
   '2025-02-04T12:00',
   '2025-02-04T13:00',
   '2025-02-04T14:00',
   '2025-02-04T15:00',
   '2025-02-04T16:00',
   '2025-02-04T17:00',
   '2025-02-04T18:00',
   '2025-02-04T19:00',
   '2025-02-04T20:00',
   '2025-02-04T21:00',
   '2025-02-04T22:00',
   '2025-02-04T23:00',
   '2025-02-05T00:00',
   '2025-02-05T01:00',
   '2025-02-05T02:00',
   '2025-02-05T03:00',
   '2025-02-05T04:00',
   '2025-02-05T05:00',
   '2025-02-05T06:00',
   '2025-02-05T07:00',
   '2025-02-05T08:00',
   '2025-02-05T09:00',
   '2025-02-05T10:00',
   '2025-02-05T11:00',
   '2025-02-05T12:00',

In [64]:
# 날씨 데이터들을 따로 추출

df = pd.DataFrame(data['hourly'])
df.head(1)

               time  temperature_2m  ...  wind_speed_10m  rain
0  2025-01-01T00:00             0.7  ...             7.3   0.0

[1 rows x 6 columns]

In [65]:
df.columns = ['측정 시간', '기온', '상대 습도', '지면 기압', '풍속', '강수량']
df.head(1)

              측정 시간   기온  상대 습도   지면 기압   풍속  강수량
0  2025-01-01T00:00  0.7     65  1018.2  7.3  0.0

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   측정 시간   8760 non-null   str
 1   기온      8760 non-null   float64
 2   상대 습도   8760 non-null   int64
 3   지면 기압   8760 non-null   float64
 4   풍속      8760 non-null   float64
 5   강수량     8760 non-null   float64
dtypes: float64(4), int64(1), str(1)
memory usage: 410.8 KB

#### 연습문제

1. 날씨 데이터에서 분류할 데이터가 존재하지 않는다.
    - 강수량 데이터를 기준으로 0보다 크다면 1(비), 아니라면 0(맑음) 데이터를 이용하여 target column 생성
    - target data의 분포 확인

2. 측정 시간 column을 시계열 데이터로 변경

3. Dataset을 만들어서 구간을 3일치 데이터(72시간)로 잡는다.

4. DataLoader를 생성, batch = 64, shuffle = False

5. LSTM 정의
    - LSTM은 기본값들을 사용, batch_first = True

6. 모델 생성, 손실 함수, 옵티마이저 구성

7. 반복 학습, epochs = 20
    - 반복마다 loss 값 출력
    - 정확도 출력 (후순위)

8. 학습된 모델을 이용하여 예측

**1**

In [67]:
df['강수량'].describe()

count    8760.000000
mean        0.145137
std         0.760927
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max        17.700000
Name: 강수량, dtype: float64

In [68]:
for i in range(len(df)):
    if df.iloc[i, 5] != 0.0:
        df.loc[i, 'target'] = 1
    else:
        df.loc[i, 'target'] = 0

In [69]:
df['target'].value_counts()

target
0.0    7506
1.0    1254
Name: count, dtype: int64

**2**

In [80]:
df['측정 시간'] = pd.to_datetime(df['측정 시간'])

In [82]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   측정 시간   8760 non-null   datetime64[us]
 1   기온      8760 non-null   float64
 2   상대 습도   8760 non-null   int64
 3   지면 기압   8760 non-null   float64
 4   풍속      8760 non-null   float64
 5   강수량     8760 non-null   float64
 6   target  8760 non-null   float64
dtypes: datetime64[us](1), float64(5), int64(1)
memory usage: 479.2 KB

**3**

In [166]:
class WindowDS(Dataset):
    def __init__(self, _x, _y, _window):
        self.x = _x
        self.y = _y
        self.window = _window
        self.n = len(_x) - _window
    def __len__(self):
        return max(self.n, 1)
    def __getitem__(self, idx):
        x = self.x[idx : idx + self.window]
        y = self.y[idx + self.window]
        x_tensor = torch.tensor(x, dtype=torch.float32)
        y_tensor = torch.tensor(y.values, dtype = torch.long)
        return x_tensor, y_tensor

In [175]:
X = df[['기온', '상대 습도', '지면 기압', '풍속']].values
y = df['target'].values

In [176]:
scaler_x = MinMaxScaler()

X = scaler_x.fit_transform(X)

In [177]:
weather_ds = WindowDS(X, y, 72)

**4**

In [178]:
train_dl = DataLoader(weather_ds, batch_size=64, shuffle=False)
train_dl

**5**

In [179]:
class WeatherLSTM(nn.Module):
    def __init__(self, input_size, hidden_size=64):
        super(WeatherLSTM, self).__init__()
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            batch_first=True
        )
        self.model = nn.Linear(hidden_size, 2),
    
    def forward(self, x):
        out, (h_n, c_n) = self.lstm(x)
        pred = self.model(h_n[-1])
        return pred

**6**

In [180]:
model = WeatherLSTM(4)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = 0.01)

In [181]:
model.train()

for epoch in range(20):
    total_loss, total_n = 0.0, 0
    for x, y in train_dl:
        pred = model(x)
        loss = criterion(pred, y)
        optimizer.zero_grad()
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        total_loss += loss.item() * y.size(0)
        total_n += y.size(0)
        _, pred = torch.max(res, 1)
    train_loss = total_loss / max(total_n, 1)

    if (epoch+1) % 5 == 0:
        print(f"Epoch: {epoch+1} / train_MSE : {round(train_loss, 6)}")

AttributeError: 'numpy.float64' object has no attribute 'values'