### 분류 문제

- 사용할 데이터셋 : data 폴더 안에 parkinsons.csv
- 사용할 모델 : RandomForest, 다중 퍼셉트론
- 종속 변수: status (0, 1)
- train, test 8:2
- 다중 퍼셉트론의 구조는 정확도 80% 이상 (epoch의 횟수는 150회로 제한)

In [11]:
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [2]:
df = pd.read_csv('../data/parkinsons.csv')
df.head(3)

,name,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
0,phon_R01_S01_1,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,...,0.06545,0.02211,21.033,1,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,phon_R01_S01_2,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,...,0.09403,0.01929,19.085,1,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,phon_R01_S01_3,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,...,0.08270,0.01309,20.651,1,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              195 non-null    str
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 17  status            195 non-null    int64
 18  RPDE              195 non-null    float64
 19  DFA               195 non-null    float64
 20  spread1           195 non-null    float64
 21  spread2           195 non-null    float64
 22  D2                195 non-null    float64
 23  PPE               195 non-null    float64
dtypes: float64(22), int64(1), str(1)
memory usage: 36.7 KB

In [4]:
df.describe()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
count,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,...,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000
mean,154.228641,197.104918,116.324631,0.006220,0.000044,0.003306,0.003446,0.009920,0.029709,0.282251,...,0.046993,0.024847,21.885974,0.753846,0.498536,0.718099,-5.684397,0.226510,2.381826,0.206552
std,41.390065,91.491548,43.521413,0.004848,0.000035,0.002968,0.002759,0.008903,0.018857,0.194877,...,0.030459,0.040418,4.425764,0.431878,0.103942,0.055336,1.090208,0.083406,0.382799,0.090119
min,88.333000,102.145000,65.476000,0.001680,0.000007,0.000680,0.000920,0.002040,0.009540,0.085000,...,0.013640,0.000650,8.441000,0.000000,0.256570,0.574282,-7.964984,0.006274,1.423287,0.044539
25%,117.572000,134.862500,84.291000,0.003460,0.000020,0.001660,0.001860,0.004985,0.016505,0.148500,...,0.024735,0.005925,19.198000,1.000000,0.421306,0.674758,-6.450096,0.174351,2.099125,0.137451
50%,148.790000,175.829000,104.315000,0.004940,0.000030,0.002500,0.002690,0.007490,0.022970,0.221000,...,0.038360,0.011660,22.085000,1.000000,0.495954,0.722254,-5.720868,0.218885,2.361532,0.194052
75%,182.769000,224.205500,140.018500,0.007365,0.000060,0.003835,0.003955,0.011505,0.037885,0.350000,...,0.060795,0.025640,25.075500,1.000000,0.587562,0.761881,-5.046192,0.279234,2.636456,0.252980
max,260.105000,592.030000,239.170000,0.033160,0.000260,0.021440,0.019580,0.064330,0.119080,1.302000,...,0.169420,0.314820,33.047000,1.000000,0.685151,0.825288,-2.434031,0.450493,3.671155,0.527367

In [132]:
X = df.drop(['name', 'status'], axis = 1)
y = df['status']

In [133]:
X.corr()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
MDVP:Fo(Hz),1.000000,0.400985,0.596546,-0.118003,-0.382027,-0.076194,-0.112165,-0.076213,-0.098374,-0.073742,...,-0.077774,-0.094732,-0.021981,0.059144,-0.383894,-0.446013,-0.413738,-0.249450,0.177980,-0.372356
MDVP:Fhi(Hz),0.400985,1.000000,0.084951,0.102086,-0.029198,0.097177,0.091126,0.097150,0.002281,0.043465,...,0.004937,-0.003733,0.163766,-0.024893,-0.112404,-0.343097,-0.076658,-0.002954,0.176323,-0.069543
MDVP:Flo(Hz),0.596546,0.084951,1.000000,-0.139919,-0.277815,-0.100519,-0.095828,-0.100488,-0.144543,-0.119089,...,-0.107293,-0.150737,-0.108670,0.210851,-0.400143,-0.050406,-0.394857,-0.243829,-0.100629,-0.340071
MDVP:Jitter(%),-0.118003,0.102086,-0.139919,1.000000,0.935714,0.990276,0.974256,0.990276,0.769063,0.804289,...,0.758255,0.746635,0.906959,-0.728165,0.360673,0.098572,0.693577,0.385123,0.433434,0.721543
MDVP:Jitter(Abs),-0.382027,-0.029198,-0.277815,0.935714,1.000000,0.922911,0.897778,0.922913,0.703322,0.716601,...,0.648793,0.697170,0.834972,-0.656810,0.441839,0.175036,0.735779,0.388543,0.310694,0.748162
MDVP:RAP,-0.076194,0.097177,-0.100519,0.990276,0.922911,1.000000,0.957317,1.000000,0.759581,0.790652,...,0.737455,0.744919,0.919521,-0.721543,0.342140,0.064083,0.648328,0.324407,0.426605,0.670999
MDVP:PPQ,-0.112165,0.091126,-0.095828,0.974256,0.897778,0.957317,1.000000,0.957319,0.797826,0.839239,...,0.804139,0.763592,0.844604,-0.731510,0.333274,0.196301,0.716489,0.407605,0.412524,0.769647
Jitter:DDP,-0.076213,0.097150,-0.100488,0.990276,0.922913,1.000000,0.957319,1.000000,0.759555,0.790621,...,0.737439,0.744901,0.919548,-0.721494,0.342079,0.064026,0.648328,0.324377,0.426556,0.671005
MDVP:Shimmer,-0.098374,0.002281,-0.144543,0.769063,0.703322,0.759581,0.797826,0.759555,1.000000,0.987258,...,0.950083,0.987626,0.722194,-0.835271,0.447424,0.159954,0.654734,0.452025,0.507088,0.693771
MDVP:Shimmer(dB),-0.073742,0.043465,-0.119089,0.804289,0.716601,0.790652,0.839239,0.790621,0.987258,1.000000,...,0.960977,0.963202,0.744477,-0.827805,0.410684,0.165157,0.652547,0.454314,0.512233,0.695058
Shimmer:APQ3,-0.094717,-0.003743,-0.150747,0.746625,0.697153,0.744912,0.763580,0.744894,0.987625,0.963198,...,0.896645,1.000000,0.716207,-0.827123,0.435242,0.151124,0.610967,0.402243,0.467265,0.645377
Shimmer:APQ5,-0.070682,-0.009997,-0.101095,0.725561,0.648961,0.709927,0.786780,0.709907,0.982835,0.973751,...,0.949146,0.960072,0.658080,-0.813753,0.399903,0.213873,0.646809,0.457195,0.502174,0.702456
MDVP:APQ,-0.077774,0.004937,-0.107293,0.758255,0.648793,0.737455,0.804139,0.737439,0.950083,0.960977,...,1.000000,0.896647,0.694019,-0.800407,0.451379,0.157276,0.673158,0.502188,0.536869,0.721694
Shimmer:DDA,-0.094732,-0.003733,-0.150737,0.746635,0.697170,0.744919,0.763592,0.744901,0.987626,0.963202,...,0.896647,1.000000,0.716215,-0.827130,0.435237,0.151132,0.610971,0.402223,0.467261,0.645389
NHR,-0.021981,0.163766,-0.108670,0.906959,0.834972,0.919521,0.844604,0.919548,0.722194,0.744477,...,0.694019,0.716215,1.000000,-0.714072,0.370890,-0.131882,0.540865,0.318099,0.470949,0.552591
HNR,0.059144,-0.024893,0.210851,-0.728165,-0.656810,-0.721543,-0.731510,-0.721494,-0.835271,-0.827805,...,-0.800407,-0.827130,-0.714072,1.000000,-0.598736,-0.008665,-0.673210,-0.431564,-0.601401,-0.692876
RPDE,-0.383894,-0.112404,-0.400143,0.360673,0.441839,0.342140,0.333274,0.342079,0.447424,0.410684,...,0.451379,0.435237,0.370890,-0.598736,1.000000,-0.110950,0.591117,0.479905,0.236931,0.545886
DFA,-0.446013,-0.343097,-0.050406,0.098572,0.175036,0.064083,0.196301,0.064026,0.159954,0.165157,...,0.157276,0.151132,-0.131882,-0.008665,-0.110950,1.000000,0.195668,0.166548,-0.165381,0.270445
spread1,-0.413738,-0.076658,-0.394857,0.693577,0.735779,0.648328,0.716489,0.648328,0.654734,0.652547,...,0.673158,0.610971,0.540865,-0.673210,0.591117,0.195668,1.000000,0.652358,0.495123,0.962435
spread2,-0.249450,-0.002954,-0.243829,0.385123,0.388543,0.324407,0.407605,0.324377,0.452025,0.454314,...,0.502188,0.402223,0.318099,-0.431564,0.479905,0.166548,0.652358,1.000000,0.523532,0.644711
D2,0.177980,0.176323,-0.100629,0.433434,0.310694,0.426605,0.412524,0.426556,0.507088,0.512233,...,0.536869,0.467261,0.470949,-0.601401,0.236931,-0.165381,0.495123,0.523532,1.000000,0.480585
PPE,-0.372356,-0.069543,-0.340071,0.721543,0.748162,0.670999,0.769647,0.671005,0.693771,0.695058,...,0.721694,0.645389,0.552591,-0.692876,0.545886,0.270445,0.962435,0.644711,0.480585,1.000000

In [134]:
y.value_counts()

status
1    147
0     48
Name: count, dtype: int64

In [135]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42, stratify = y
)

In [136]:
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

X_train_tensor = torch.tensor(X_train_sc, dtype = torch.float32)
X_test_tensor = torch.tensor(X_test_sc, dtype = torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype = torch.long)
y_test_tensor = torch.tensor(y_test.values, dtype = torch.long)

In [158]:
rfclf = RandomForestClassifier(random_state=42, n_estimators=500)

rfclf.fit(X_train_sc, y_train)
pred_rf = rfclf.predict(X_test_sc)

print('정확도:', round(accuracy_score(y_test, pred_rf), 4))
print(classification_report(y_test, pred_rf))

정확도: 0.9231
              precision    recall  f1-score   support

           0       0.89      0.80      0.84        10
           1       0.93      0.97      0.95        29

    accuracy                           0.92        39
   macro avg       0.91      0.88      0.90        39
weighted avg       0.92      0.92      0.92        39

In [138]:
class clf(nn.Module):
    def __init__(self, _dim):
        super(clf, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(_dim, _dim*3),
            nn.ReLU(),
            nn.Linear(_dim*3, _dim*2),
            nn.ReLU(),
            nn.Linear(_dim*2, 2)
        )
    
    def forward(self, x):
        return self.model(x)

In [139]:
model = clf(X_test_tensor.shape[1])
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [140]:
model.train()

for epoch in range(150):
    pred = model(X_train_tensor)
    loss = criterion(pred, y_train_tensor)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1)%20 == 0:
        print(f'Epoch {epoch+1}, Loss: {round(loss.item(), 6)}')

Epoch 20, Loss: 0.441697
Epoch 40, Loss: 0.340111
Epoch 60, Loss: 0.266184
Epoch 80, Loss: 0.203745
Epoch 100, Loss: 0.147719
Epoch 120, Loss: 0.101857
Epoch 140, Loss: 0.069001

In [141]:
model.eval()

with torch.no_grad():
    pred = model(X_test_tensor)
    _, pred_idx = torch.max(pred, 1)
    acc = accuracy_score(y_test_tensor, pred_idx)
    print(f'Test Accuracy: {round(acc, 4)}')
    print(classification_report(y_test_tensor, pred_idx))

Test Accuracy: 0.9744
              precision    recall  f1-score   support

           0       0.91      1.00      0.95        10
           1       1.00      0.97      0.98        29

    accuracy                           0.97        39
   macro avg       0.95      0.98      0.97        39
weighted avg       0.98      0.97      0.97        39

In [142]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold, GridSearchCV

In [143]:
pipe = Pipeline(
    [
        ( 'scaler', StandardScaler() ),     # step 1
        ( 'model', RandomForestClassifier(random_state=42) )                  # step 2

    ], verbose = True
)

pipe

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', RandomForestClassifier(random_state=42))],
         verbose=True)

In [144]:
params = {
    'model__n_estimators' : [50, 100, 200],
    'model__max_depth' : [None, 10, 20],
    'model__min_samples_split' : [2, 5, 10]
}

In [145]:
cv_fold = StratifiedKFold(shuffle=True, random_state=42)

In [146]:
grid_clf = GridSearchCV(
    estimator= pipe,                # 파이프라인으로 생성한 모델을 지정
    param_grid= params,             # dict 형태로 파라미터의 조합
    scoring = 'accuracy',           # 베스트 모델 선정 기준
    cv = cv_fold,                   # 생성해둔 KFold 지정
    refit = True,                   # 재학습 여부
    n_jobs = -1,                    # 모든 CPU를 사용
    return_train_score= True,       # 학습 데이터의 성능을 출력
    verbose = 2                     # 로그 표시를 상세하게
)

In [147]:
grid_clf.fit(X_train, y_train)

Fitting 5 folds for each of 27 candidates, totalling 135 fits

[Pipeline] ............ (step 1 of 2) Processing scaler, total=   0.0s
[Pipeline] ............. (step 2 of 2) Processing model, total=   0.4s

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model',
                                        RandomForestClassifier(random_state=42))],
                                verbose=True),
             n_jobs=-1,
             param_grid={'model__max_depth': [None, 10, 20],
                         'model__min_samples_split': [2, 5, 10],
                         'model__n_estimators': [50, 100, 200]},
             return_train_score=True, scoring='accuracy', verbose=2)

In [148]:
print(grid_clf.best_params_)

{'model__max_depth': None, 'model__min_samples_split': 2, 'model__n_estimators': 200}

In [149]:
pred = grid_clf.predict(X_test)

In [150]:
best_rf = RandomForestClassifier(random_state=42, min_samples_split=2, n_estimators=200, max_depth=None)
best_rf.fit(X_train_sc, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [151]:
feature_df = pd.DataFrame(zip(X_train.columns, best_rf.feature_importances_),
             columns=['feature_name', 'importance'])
feature_df.sort_values('importance', ascending=False).head(5)

   feature_name  importance
21          PPE    0.150716
18      spread1    0.109254
0   MDVP:Fo(Hz)    0.060157
7    Jitter:DDP    0.057883
14          NHR    0.056363

In [152]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.89      0.80      0.84        10
           1       0.93      0.97      0.95        29

    accuracy                           0.92        39
   macro avg       0.91      0.88      0.90        39
weighted avg       0.92      0.92      0.92        39