In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score

In [3]:
df = pd.read_csv('../data2/Alternative.csv', index_col = 0)
df.head(3)

      TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3

In [4]:
X = df.drop('sales', axis = 1)
y = df['sales']

In [12]:
# interaction_only → 상호작용항들만 사용할 것인가?
# include_bias → 상수항인 컬럼을 추가할 것인가?

poly = PolynomialFeatures(degree = 2, interaction_only= True, include_bias=False)
# pd.DataFrame(poly.fit_transform(X))
X_poly = poly.fit_transform(X)

In [13]:
poly_columns = poly.get_feature_names_out(X.columns)
poly_columns

array(['TV', 'radio', 'newspaper', 'TV radio', 'TV newspaper',
       'radio newspaper'], dtype=object)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X_poly, y, test_size = 0.2, random_state = 42
)

In [15]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
model = Ridge()
model.fit(X_train, y_train)
pred = model.predict(X_test)
print(round(r2_score(y_test, pred), 2))

0.97

In [21]:
coef_df = pd.DataFrame(
    {
        'feature_names' : poly_columns,
        'coefficient' : model.coef_
    }
).sort_values('coefficient', ascending = False)

coef_df

     feature_names  coefficient
3         TV radio     3.510619
0               TV     1.761130
1            radio     0.527695
2        newspaper     0.296262
5  radio newspaper    -0.119551
4     TV newspaper    -0.250750